# config.yaml

openai_model: "gpt-4.1-2025-04-14" # Ваша указанная модель

default_system_prompt: |
  Ты — ИИ-ассистент, эксперт по анализу финансовых данных и извлечению информации.
  Твоя задача — внимательно проанализировать предоставленный контекст и точно заполнить поля указанной Pydantic модели (инструмента).
  Руководствуйся описаниями полей в модели для корректной классификации и извлечения данных.

user_prompt_template: |
  **Задача: Анализ и структурирование данных**

  **Контекст для анализа:**
  ---
  {tags_context}
  ---
  На основе *только* приведенного выше `tags_context`, проанализируй информацию.
  Заполни поля Pydantic модели (инструмента) с именем: '{tool_name}'.
  Строго следуй структуре, типам данных и описаниям полей модели '{tool_name}'.
  Не додумывай информацию, отсутствующую в контексте. Если данные для поля отсутствуют, используй значение по умолчанию из модели или оставь поле незаполненным, если это допустимо.
tags_context_ved: |
  Описания транзакций для анализа:
  ---
  {sample_descriptions}
  ---
  Вопрос: Есть ли в этих данных явные признаки внешнеэкономической деятельности (ВЭД)?
  Признаки: платежи в иностранной валюте, SWIFT, иностранные контрагенты, таможня, валютный контроль.
  Если да, укажи краткое обоснование.
ags_context_cash: |
  Анализируемые данные:
  1. Описания транзакций:
  ---
  {sample_descriptions}
  ---
  2. {additional_cash_info_str}

  Вопрос: Определи уровень активности операций с наличными (cash_activity_level).
  Ожидаемые значения: 'high' (частые/крупные операции с наличными или значительные кассовые комиссии) или 'low' (преобладают безналичные расчеты).
payments_context:
  Необходимо проанализировать предоставленные ниже описания банковских транзакций компании.
  Цель — определить наличие следующих типов платежей:
  - Платежи поставщикам (например, оплата по счету, за товары/услуги, за материалы).
  - Выплаты, связанные с заработной платой (например, перечисление зарплаты, аванс).
  - Налоговые платежи (например, оплата налога, пени ФНС, взносы в ПФР).

  Описания транзакций:
  ---
  {sample_descriptions}
  ---
  Проанализируй эти транзакции и определи, какие из указанных выше типов платежей присутствуют.